### ISSUE TITLE
Request for detailed report

### ISSUE THREAD

**Issue by paveljee** [EPPI-Centre/AI-equity#1]
Hi James,

Thanks so much for sharing this intriguing piece of research and data. Both screening and extraction conducted entirely by a LLM – how exciting! I did note the original TSV file with the search results, but I was wondering if you could also share the full search strategy?

Also, you were mentioning in the summary that some Se and Sp metrics were calculated with human validation – could you please also share details on those? As well as the specs of the model – I assume that at the time you ran the analysis that was before the release of GPT-4o?

I understand that a manuscript might as well be in the works, and sorry if I missed any of the materials available elsewhere.

Thanks in advance!

P.S. I came here from the recent Cochrane webinar, which I learned about from a newsletter after it passed but was able to access the [slide deck](https://training.cochrane.org/sites/training.cochrane.org/files/public/uploads/James%20Thomas_part%202.pdf) from the [Artificial intelligence (AI) technologies in Cochrane](https://training.cochrane.org/resource/artificial-intelligence-technologies-in-cochrane) page.

**Comment by j-thomas-ucl** [comment]
Hi Pavel,

We’re writing up a paper on this now which contains all the information you’re looking for. I can send you the search strategy direct if you need it soon though?

Best wishes, James.

From: Pavel Zhelnov ***@***.***>
Date: Friday, 17 May 2024 at 22:08
To: EPPI-Centre/AI-equity ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EPPI-Centre/AI-equity] Request for detailed report (Issue #1)

⚠ Caution: External sender


Hi James,

Thanks so much for sharing this intriguing piece of research and data. Both screening and extraction conducted entirely by a LLM – how exciting! I did note the original TSV file with the search results, but I was wondering if you could also share the full search strategy?

Also, you were mentioning in the summary that some Se and Sp metrics were calculated with human validation – could you please also share details on those? As well as the specs of the model – I assume that at the time you ran the analysis that was before the release of GPT-4o?

I understand that a manuscript might as well be in the works, and sorry if I missed any of the materials available elsewhere.

Thanks in advance!

P.S. I came here from the recent Cochrane webinar, which I learned about from a newsletter after it passed but was able to access the slide deck<https://training.cochrane.org/sites/training.cochrane.org/files/public/uploads/James%20Thomas_part%202.pdf> from the Artificial intelligence (AI) technologies in Cochrane<https://training.cochrane.org/resource/artificial-intelligence-technologies-in-cochrane> page.

**Comment by paveljee** [comment]
> I can send you the search strategy direct if you need it soon though? 

Yes, that would be amazing! I can be reached via GitHub or email <pavel@zheln.com>. Thank you so much!
